-- MySQL Script generated by MySQL Workbench
-- Wed Apr  5 11:28:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_controle
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_controle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_controle` DEFAULT CHARACTER SET utf8 ;
USE `bd_controle` ;

-- -----------------------------------------------------
-- Table `bd_controle`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_controle`.`departamento` (
  `ID_DEPTO` INT(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_DEPTO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_controle`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_controle`.`empresa` (
  `ID_EMPRESA` INT(11) NOT NULL AUTO_INCREMENT,
  `DOC_EMPRESA` CHAR(18) NOT NULL,
  `NOME_EMPRESA` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_EMPRESA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_controle`.`equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_controle`.`equipamento` (
  `ID_EQUIPAMENTO` INT(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(45) NULL DEFAULT NULL,
  `MODELO` VARCHAR(45) NULL DEFAULT NULL,
  `MARCA` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_EQUIPAMENTO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_controle`.`software`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_controle`.`software` (
  `ID_SOFTWARE` INT(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(150) NULL DEFAULT NULL,
  `NUM_LICENCA` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_SOFTWARE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_controle`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_controle`.`estoque` (
  `PATRIMONIO` INT(11) NOT NULL,
  `ID_EQUIPAMENTO` INT(11) NULL DEFAULT NULL,
  `ID_SOFTWARE` INT(11) NULL DEFAULT NULL,
  `QUANTIDADE` INT(11) NULL DEFAULT NULL,
  `DATA_ENTRADA` DATE NULL DEFAULT NULL,
  `DATA_SAIDA` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`PATRIMONIO`),
  INDEX `fk_ESTOQUE_SOFTWARE1_idx` (`ID_SOFTWARE` ASC),
  INDEX `fk_ESTOQUE_EQUIPAMENTO1_idx` (`ID_EQUIPAMENTO` ASC),
  CONSTRAINT `fk_ESTOQUE_EQUIPAMENTO1`
    FOREIGN KEY (`ID_EQUIPAMENTO`)
    REFERENCES `bd_controle`.`equipamento` (`ID_EQUIPAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTOQUE_SOFTWARE1`
    FOREIGN KEY (`ID_SOFTWARE`)
    REFERENCES `bd_controle`.`software` (`ID_SOFTWARE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_controle`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_controle`.`fornecedor` (
  `ID_FORN` INT(11) NOT NULL AUTO_INCREMENT,
  `DOC_FORN` CHAR(18) NULL DEFAULT NULL,
  `NOME` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_FORN`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_controle`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_controle`.`funcionario` (
  `ID_FUNC` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_DEPTO` INT(11) NOT NULL,
  `NOME_FUNC` VARCHAR(80) NOT NULL,
  `ID_EMPRESA` INT(11) NOT NULL,
  PRIMARY KEY (`ID_FUNC`),
  INDEX `fk_FUNCIONARIO_EMPRESA1_idx` (`ID_EMPRESA` ASC),
  INDEX `fk_FUNCIONARIO_DEPARTAMENTO1_idx` (`ID_DEPTO` ASC),
  CONSTRAINT `fk_FUNCIONARIO_DEPARTAMENTO1`
    FOREIGN KEY (`ID_DEPTO`)
    REFERENCES `bd_controle`.`departamento` (`ID_DEPTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FUNCIONARIO_EMPRESA1`
    FOREIGN KEY (`ID_EMPRESA`)
    REFERENCES `bd_controle`.`empresa` (`ID_EMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_controle`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_controle`.`nota` (
  `ID_NOTA` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_EQUIPAMENTO` INT(11) NOT NULL,
  `ID_FORN` INT(11) NOT NULL,
  `DATA_COMPRA` DATE NULL DEFAULT NULL,
  `VALOR` FLOAT NOT NULL,
  PRIMARY KEY (`ID_NOTA`),
  INDEX `fk_NOTA_EQUIPAMENTO1_idx` (`ID_EQUIPAMENTO` ASC),
  INDEX `fk_NOTA_FORNECEDOR1_idx` (`ID_FORN` ASC),
  CONSTRAINT `fk_NOTA_EQUIPAMENTO1`
    FOREIGN KEY (`ID_EQUIPAMENTO`)
    REFERENCES `bd_controle`.`equipamento` (`ID_EQUIPAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTA_FORNECEDOR1`
    FOREIGN KEY (`ID_FORN`)
    REFERENCES `bd_controle`.`fornecedor` (`ID_FORN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_controle`.`troca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_controle`.`troca` (
  `ID_TROCA` INT(11) NOT NULL AUTO_INCREMENT,
  `PATRIMONIO` INT(11) NULL DEFAULT NULL,
  `ID_FUNC` INT(11) NULL DEFAULT NULL,
  `ID_EQUIPAMENTO` INT(11) NULL DEFAULT NULL,
  `DT_ULTIMA_TROCA` DATE NULL DEFAULT NULL,
  `DT_PROXIMA_TROCA` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID_TROCA`),
  INDEX `fk_TROCA_FUNCIONARIO1_idx` (`ID_FUNC` ASC),
  INDEX `fk_TROCA_ESTOQUE1_idx` (`PATRIMONIO` ASC),
  INDEX `fk_TROCA_EQUIPAMENTO1_idx` (`ID_EQUIPAMENTO` ASC),
  CONSTRAINT `fk_TROCA_EQUIPAMENTO1`
    FOREIGN KEY (`ID_EQUIPAMENTO`)
    REFERENCES `bd_controle`.`equipamento` (`ID_EQUIPAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TROCA_ESTOQUE1`
    FOREIGN KEY (`PATRIMONIO`)
    REFERENCES `bd_controle`.`estoque` (`PATRIMONIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TROCA_FUNCIONARIO1`
    FOREIGN KEY (`ID_FUNC`)
    REFERENCES `bd_controle`.`funcionario` (`ID_FUNC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_controle`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_controle`.`usuario` (
  `ID_USUARIO` INT(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(16) NOT NULL,
  `PASSWORD` VARCHAR(32) NOT NULL,
  `TIPO` INT(11) NOT NULL,
  PRIMARY KEY (`ID_USUARIO`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
